apiVersion: v1
kind: Service
metadata:
  name: service-back-ecoliza
  labels: 
    app: ecoliza-backend
spec:
  selector:
    app: ecoliza-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: NodePort